---
- hosts: fortimanager
  collections:
   - fortinet.fortimanager
   - ansible.builtin.httpapi 
  gather_facts: no
  tasks:
      
   - name: retrieve all the scripts
     fortinet.fortimanager.fmgr_fact:
       facts:
           selector: 'dvmdb_script'
           params:
               adom: 'root'
               script: ''     
     register: facts

   - name: Print data
     debug:
       msg: "{{ facts }}"
