---
- hosts: ip-172-31-20-205.eu-west-1.compute.internal
  gather_facts: no
  tasks:
  - name: fortios_firewall_internet_service
    fortios_firewall_internet_service:
      vdom: root
      state: present
      firewall_internet_service:
        database: isdb
        direction: dst
        extra_ip_range_number: 0
        icon_id: 114
        id: 7471105
        ip_number: 0
        ip_range_number: 0
        name: Okta-Web
        obsolete: 0
        reputation: 0
        singularity: 0
        sld_id: 0
