---
- hosts: fortigate
  collections:
   - fortinet.fortios
  connection: httpapi
  gather_facts: no
  vars:
   vdom: "root"
   ansible_httpapi_use_ssl: yes
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 443
  tasks:
      
  - name: Configure devices.
    fortios_firewall_policy:
      vdom:  root
      state: "{{ state }}"
      firewall_policy:
        policyid: "{{ pid }}"
        srcintf:
          - name: "{{ psource }}"
        dstintf:
          - name: "{{ pdest }}"
        srcaddr:
          - name: all
        dstaddr:
          - name: all
        action: accept
        service:
          - name: ALL
        name: "{{ pname }}"
        status: enable
        schedule: always
        logtraffic: all
        logtraffic_start: disable
     
