---
- hosts: fortigate
  collections:
   - fortinet.fortios
  gather_facts: no
  tasks:
  
  - name: Configure devices.
    fortios_firewall_policy:
      vdom:  root
      state: "{{ state }}"
      firewall_policy:
        policyid: "{{ pid }}"
        srcintf:
          - name: "{{ psource }}"
        dstintf:
          - name: "{{ pdest }}"
        srcaddr:
          - name: all
        dstaddr:
          - name: all
        action: accept
        service:
          - name: ALL
        name: "{{ pname }}"
        status: enable
        schedule: always
        logtraffic: all
        logtraffic_start: disable
     
